# Desecration

ASide:
  - Room: "RG2_0"
    Holes:
    - Side: Down
      Idx: 0
      Kind: out
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "RG2_1"
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Dashes: one
        Difficulty: normal
      ReqIn:
        Or:
        - Dashes: one
          Flag: poweroff:set
          Difficulty: hard
        - Dashes: one
          Difficulty: expert
        - Dashes: two
          Difficulty: normal
    Tweaks:
    - Name: "invisibleBarrier"
      Update:
        Remove: true
    - Name: "exitBlock" 
      Update:
        Remove: true
      
  - Room: "RG2_2"
    Holes:
    - Side: Left
      Idx: 1
      Kind: inout
    - Side: Up
      Idx: 1
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Side: Down
      Idx: 0
      Kind: inout
      Launch: -1
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
      
  - Room: "RG2_3"
    Holes:
    - Side: Down
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 3
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "FactoryHelper/RustyJumpthruPlatform"
      X: 72
      Y: 168
      Update:
        X: 80
        Width: 40
    - Name: "invisibleBarrier" # stop box from yeeting offscreen if no filler room above
      Update:
        Add: true
        X: 576
        Y: -8
        Width: 32
        Height: 8
      
  - Room: "RG2_4"
    Holes:
    - Side: Down
      Idx: 4
      Kind: in
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "breaker"
      ReqBoth:
        Flag: sc2020_rocketguy_fuse:set
        Or:
        - Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
    - To: "fuse"
      ReqBoth:
        Or:
        - Dashes: zero
          Difficulty: expert
          Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Or:
        - Dashes: zero
          Difficulty: hard
          Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
    Subrooms:
    - Room: "breaker"
      Flags:
      - poweroff:set
      InternalEdges:
      - To: "exit"
        ReqBoth:
          Or:
          - Flag: poweroff:set
          - Dashes: one
            Difficulty: normal
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    - Room: "fuse"
      Flags:
      - sc2020_rocketguy_fuse:set
    Tweaks:
    - Name: "jumpThru"
      ID: 137
      Update:
        Width: 32
    - Name: "spawn"
      X: 1408
      Y: 168
      Update:
        Default: true
    - Name: "exitBlock" # blocks off switch, flag unused
      Update:
        Add: true
        X: 160
        Y: 56
        Width: 80
        Height: 64
        Values:
          tileType: "G" # Reflection Alt
    - Name: "spawn"
      Update:
        Add: true
        X: 1816
        Y: 128
      
  - Room: "RG2_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: expert
        - Dashes: one
          Difficulty: normal
    Subrooms:
    - Room: "berry" # make berry inaccessible, won't use flag
      Collectables:
      - Idx: 0
    Tweaks:
    - Name: "changeRespawnTrigger"
      X: 1160
      Y: 16
      Update:
        Remove: true
      
  - Room: "RG2_5s"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none