# Intermediate Heart Side

ASide:
  - Room: "int_heart_00"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
        
  - Room: "int_heart_01"
    Holes:
    - Side: Left
      Idx: 8
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 1
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Left
      Idx: 3
      Kind: none
    - Side: Left
      Idx: 4
      Kind: none
    - Side: Left
      Idx: 5
      Kind: none
    - Side: Left
      Idx: 6
      Kind: none
    - Side: Left
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 56
      Y: 1144
      Update:
        Default: true
    
  - Room: "int_heart_02"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
    - Name: "spawn"
      X: 86
      Y: 1432
      Update:
        Default: true
        
  - Room: "int_heart_03"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 1
      Kind: out
      ReqOut:
        Key: true
        KeyholeID: 3081
        Dashes: two
        Difficulty: hard
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: hard
    Tweaks:
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
    - Name: "spawn"
      X: 76
      Y: 1400
      Update:
        Default: true
        
  - Room: "int_heart_04"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "spawn"
      X: 148
      Y: 1256
      Update:
        Default: true
      
  - Room: "int_heart_05"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Down
      Idx: 1
      Kind: out
      LowBound: 181
      HighOpen: true
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
    - Name: "luaCutscenes/luaCutsceneTrigger"
      X: 24
      Y: 360
      Update:
        Remove: true
        
  - Room: "int_heart_06"
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Holes:
    - Side: Up
      Idx: 0
      Kind: in
      LowBound: 19
      HighBound: 27
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    Tweaks:
    - Name: "luaCutscenes/luaCutsceneTrigger"
      X: 40
      Y: 40
      Update:
        Remove: true