# Space Jam Fever Dream

ASide:
  # cruor_00 cut, not interesting intro
      
  - Room: "cruor_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "demo"
      ReqBoth:
        Dashes: one
        Difficulty: expert
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "demo"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - To: "exit"
        ReqOut:
          Dashes: one
          Difficulty: normal
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 1
        Kind: out
    Tweaks:
    - Name: "spawn"
      X: 632
      Y: 240
      Update:
        X: 624
    - Name: "dreamBlock"
      ID: 51
      Update:
        Width: 224
    - Name: "lightbeam"
      Update:
        Remove: true
    - Name: "cameraOffsetTrigger"
      ID: 680
      Update:
        Remove: true
    - Name: "cameraOffsetTrigger"
      ID: 681
      Update:
        Remove: true
    - Name: "cameraTargetTrigger"
      Update:
        Add: true
        X: 256
        Y: 176
        Width: 32
        Height: 144
        Nodes:
        - Idx: 0
          X: 264
          Y: 240
        Values:
          lerpStrength: 1.0
    - Name: "cameraOffsetTrigger"
      ID: 548
      Update:
        X: 272
        Width: 8
    - Name: "cameraOffsetTrigger"
      Update:
        Add: true
        X: 264
        Y: 176
        Width: 8
        Height: 144
    - Name: "everest/smoothCameraOffsetTrigger"
      X: 568
      Y: 112
      Update:
        Remove: true
    - Name: "cameraTargetTrigger"
      Update:
        Add: true
        X: 592
        Y: 112
        Width: 32
        Height: 128
        Nodes:
        - Idx: 0
          X: 600
          Y: 184
        Values:
          lerpStrength: 1.0
    - Name: "cameraOffsetTrigger"
      ID: 193
      Update:
        X: 608
        Width: 16
    - Name: "cameraOffsetTrigger"
      Update:
        Add: true
        X: 592
        Y: 112
        Width: 16
        Height: 128
        Values:
          cameraX: -1.0
          
  # - Room: "cruor_01a" # currently disabled due to Lua cutscene disable movement
    # Holes:
    # - Side: Left
      # Idx: 0
      # Kind: in
    # InternalEdges: 
    # - CustomWarp: true
      # ReqOut:
        # Dashes: zero

  - Room: "cruor_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right # Requires "opened_pandoras_box" unset
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Right # Requires "opened_pandoras_box" set
      Idx: 1
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 96
      Y: 136
      Update:
        Default: true
      
  - Room: "cruor_03_bp"
    ReqEnd:
      Or:
      - Dashes: one
        Difficulty: hard
      - Dashes: two
        Difficulty: normal
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 1780
        Y: 64
       
  - Room: "cruor_03_tp"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exit"
      ReqOut:
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
      InternalEdges:
      - Collectable: 0
        ReqBoth:
          Dashes: one
          Difficulty: normal
          
  - Room: "cruor_04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Up
      Idx: 0
      Kind: inout
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    InternalEdges:
    - Split: BottomToTop
      ReqOut:
        Dashes: one
        Difficulty: normal
      
  # cruor_05 cut, uninteresting outro