Backgrounds:
# Opaque
- Texture: "bgs/1up2020CollabBgs/bg00_VRWall"
  Opaque: true
  LoopY: true
  ScrollFactorX: 0.5
  ScrollFactorY: 0.0
  SpeedX: -12.0
  SpeedY: 12.0
- Texture: "bgs/CANADIAN/warpedcitybg"
  Opaque: true
  BlendMode: "additive"
  ScrollFactorX: 0.1
  ScrollFactorY: 0.0
- Texture: "bgs/CirqueMadelano/circus"
  Opaque: true
  BlendMode: "additive"
  ScrollFactorX: 0.15
  ScrollFactorY: 0.0
# Non-Opaque
- Texture: "bgs/1up2020CollabBgs/bg02_LEDGreen"
  CoverBottom: 36
  ScrollFactorX: 0.9
  ScrollFactorY: 0.0
- Texture: "bgs/Bissy/bg1"
  CoverBottom: 34
  OffY: -10
  ScrollFactorX: 0.717125
  ScrollFactorY: 0.0
- Texture: "bgs/collab/pillars"
  CoverBottom: 5
  NeedsColor: true
  ScrollFactorX: 0.3
  ScrollFactorY: 0.3
- Texture: "bgs/CANADIAN/mountains"
  CoverBottom: 53
  LoopY: true
  ScrollFactorX: 0.03
  ScrollFactorY: 0.0
- Texture: "bgs/davcollab/BG03_Tower"
  LoopX: false
  LoopY: true
  ScrollFactorX: 0.0
  ScrollFactorY: 0.1525
- Texture: "bgs/Galaksyz/shrooms01"
  CoverBottom: 122
  ScrollFactorX: 0.25
  ScrollFactorY: 0.0
- Texture: "bgs/hyper/scribbleTrees"
  CoverBottom: 33
  NeedsColor: true
  OffY: -10
  ScrollFactorX: 0.9
  ScrollFactorY: 0.9

Campaigns:
- Name: "Spring Collab 2020"
  LevelSets:
  - Name: "Beginner Lobby"
    ID: "SpringCollab2020/1-Beginner"
  - Name: "Intermediate Lobby"
    ID: "SpringCollab2020/2-Intermediate"
  - Name: "Advanced Lobby"
    ID: "SpringCollab2020/3-Advanced"
  - Name: "Expert Lobby"
    ID: "SpringCollab2020/4-Expert"
  - Name: "Grandmaster Lobby"
    ID: "SpringCollab2020/5-Grandmaster"
    
CollectableNames:
- "LunaticHelper/StrawberryWithReturn"
- "SpringCollab2020/returnBerry"
- "SpringCollab2020/CassetteFriendlyStrawberry"
- "SpringCollab2020/diagonalWingedStrawberry"
  
Music:
# Lobbies
- Name: "event:/collab2020/beginner_lobby"
- Name: "event:/SC2020_Int_Lobby"
- Name: "event:/SC2020_Lobby_advanced"
- Name: "event:/collab2020/expert_lobby"
- Name: "event:/SC2020_Lobby_Grandmaster"
# Beginner maps
- Name: "event:/SC2020_Jude"
- Name: "event:/collab2020/bissy_beginner"
- Name: "event:/SC2020_canadian_int"
- Name: "event:/SC2020_Cruor"
- Name: "event:/Collab2020/Flagpole1Up"
- Name: "event:/SC2020_HennyBurgr"
- Name: "event:/SC2020_dad_kevinTemple"
- Name: "event:/SC2020_Choco"
- Name: "event:/SC2020_Rue_Beginner"
- Name: "event:/SC2020_skeleton_beginner"
- Name: "event:/SC2020_TG90BEG"
# Beginner Heartside and all progression levels
# No 0 progress, it is super repetitive and I would never want to hear that in a song over and over
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 1
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 2
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 3
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 4
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 5
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 6
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 7
- Name: "event:/collab2020/heartside_beginner"
  Parameters:
    heartside_beginner_progress: 8
# Intermediate maps
- Name: "event:/SC2020_aleph_int"
- Name: "event:/SC2020_aridai_int"
- Name: "event:/SC2020_Bissy_Intermed"
- Name: "event:/SC2020_Hyper"
- Name: "event:/collab2020/donker"
- Name: "event:/SC2020_EvilLeafy"
- Name: "event:/SC2020_Goat_Collab"
- Name: "event:/SC2020_Collab_Lichtbaulb_Intermediate-3.5"
- Name: "event:/SC2020_Noax"
- Name: "event:/collab2020/oppen"
- Name: "event:/music/phant_collab"
- Name: "event:/SC2020_Rocketguy_collab"
- Name: "event:/SC2020_Collab_Skeleton_Intermediate-3.5"
- Name: "event:/SC2020_TheA_In"
- Name: "event:/SC2020_TheA_Esc"
- Name: "event:/SC2020_Thegur90_Intermediate"
- Name: "event:/SC2020_Int_Heartside"
# Advanced maps
- Name: "event:/SC2020_Collab_Sleepie_Advanced-4"
- Name: "event:/collab2020/beefy"
- Name: "event:/SC2020_Collab_Bissy_Advanced-3"
- Name: "event:/SC2020_Cookie_adv"
- Name: "event:/Dozing_Collab"
- Name: "event:/SC2020_GALAXYZ_ADV"
# The Climb has weird progression settings theres like 20 different parameters and I had to look in Ahorn
- Name: "event:/collab2020/holly"
- Name: "event:/SC2020_Dadbod_Adv"
- Name: "event:/SC2020_Linj_Adv"
- Name: "event:/SC2020_NeoKat_Nyoom"
- Name: "event:/collab2020/percussive"
- Name: "event:/SC2020_Rufus"
- Name: "event:/SC2020_Spoopy"
- Name: "event:/taco360_Collab"
- Name: "event:/SC2020_Thegur90_Advanced"
- Name: "event:/SC2020_Tortoise"
- Name: "event:/SC2020_Tortoise_Boss"
# Expert maps
- Name: "event:/SC2020_Bissy_Expert"
- Name: "event:/SC2020_Canadian_Expert"
- Name: "event:/collab2020/chaotic"
- Name: "event:/SC2020_Deskilln_Collab"
- Name: "event:/SC2020_Dadbod_Octo"
- Name: "event:/SC2020_Kube_Collab"
- Name: "event:/SC2020_LethargicDoggo"
- Name: "event:/collab2020/mun"
- Name: "event:/SC2020_Radley"
- Name: "event:/SC2020_Thejank90_Expert"
- Name: "event:/collab2020/zerex"
# Expert heartside and all its progression levels
# 0 is weighted at 0.5 due to repetitivity
- Name: "event:/collab2020/heartside_expert"
  Weight: 0.5
  Parameters:
    exh_progress: 0
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 1
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 2
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 3
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 4
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 5
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 6
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 7
- Name: "event:/collab2020/heartside_expert"
  Parameters:
    exh_progress: 8
# Grandmaster maps
- Name: "event:/SC2020_Bissy_Heck_KevinII"
- Name: "event:/SC2020_BobDole_Dustforce"
- Name: "event:/collab2020/canadian"
- Name: "event:/SC2020_Cyber_Heck_Music"
- Name: "event:/SC2020_WoofWoofDoggo"
- Name: "event:/SC2020_Hydro_Collab"
- Name: "event:/SC2020_Collab_Dadbod_Heck-3.5"
- Name: "event:/SC2020_DavTheLugia"
- Name: "event:/SC2020_Thegur90_Heck"

Rulesets:
- Name: "SCA"
  LongName: "Normal Pathway [Spring Collab, Beginner] (A)"
  Algorithm: "Pathway"
  Difficulty: "Normal"
  Length: "Medium"
  Darkness: "Never"
  EnabledMaps:
  - SID: "SpringCollab2020/1-Beginner/Abby"
    Mode: 0 # A-side
  - SID: "SpringCollab2020/1-Beginner/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/CANADIAN"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Cat_in_Box_01"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Cookie"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Cruor"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/DanTKO"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Flagpole1up"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Ghajestis"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/hennyburgr"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/IsaGoodFriend"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/itsabrody"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Lichtbaulb"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Rue"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Skeleton"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Snas"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/ZZ-HeartSide"
    Mode: 0
- Name: "SCB"
  LongName: "Hard Pathway [Spring Collab, Intermediate] (B)"
  Algorithm: "Pathway"
  Difficulty: "Hard"
  Length: "Medium"
  Darkness: "Never"
  EnabledMaps:
  - SID: "SpringCollab2020/2-Intermediate/aleph_null"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/aridai"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Bonicle"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Clover"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Donker19"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Evilleafy"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/GG19"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Goat"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Hallow"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/hennyburgr"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Lichtbaulb"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Noax"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Oppen_Heimer"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/phant"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/ProXas"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Rocketguy2"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/SilverStar"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Skeleton"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/TheAdvertisement"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/ZZ-HeartSide"
    Mode: 0
- Name: "SCC"
  LongName: "Hard Pathway [Spring Collab, Advanced] (C)"
  Algorithm: "Pathway"
  Difficulty: "Hard"
  Length: "Medium"
  Darkness: "Never"
  EnabledMaps:
  - SID: "SpringCollab2020/3-Advanced/_sleepie"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/BeefyUncle"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Cookie"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Dozing"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Ezel"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Galaksyz"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Holly"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/JaThePlayer"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/LinjKarma"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/NeoKat"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/orbittwz"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Percussive"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/RealVet"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Rufus"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Spoopy"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/taco360"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Tortoise"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/ZZ-HeartSide"
- Name: "SCD"
  LongName: "Expert Pathway [Spring Collab, Expert] (D)"
  Algorithm: "Pathway"
  Difficulty: "Expert"
  Length: "Medium"
  Darkness: "Never"
  EnabledMaps:
  - SID: "SpringCollab2020/4-Expert/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/CANADIAN"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/ChaotiC"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/dahlukeh"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/DeathKontrol"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/deskilln"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Indecx"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Kube"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/LethargicDoggo"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Mineman"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Mun"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/RadleyMcTuneston"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Zerex"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/ZZ-HeartSide"
    Mode: 0
- Name: "SCE"
  LongName: "Master Pathway [Spring Collab, Grandmaster] (E)"
  Algorithm: "Pathway"
  Difficulty: "Master"
  Length: "Medium"
  Darkness: "Never"
  EnabledMaps:
  - SID: "SpringCollab2020/5-Grandmaster/1nkFa1c0n"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/BobDole"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/CANADIAN"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Cyber"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/DeathKontrol"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/dog"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/fishtank_overflow"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Hydro0"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Problemstrol"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/TheDavSmasher"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/ZZ-HeartSide"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/ZZ-NewHeartSide"
    Mode: 0
- Name: "SCF"
  LongName: "Expert Pathway [Spring Collab, All] (F)"
  Algorithm: "Pathway"
  Difficulty: "Expert"
  Length: "Medium"
  Darkness: "Never"
  EnabledMaps:
  - SID: "SpringCollab2020/1-Beginner/Abby"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/CANADIAN"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Cat_in_Box_01"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Cookie"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Cruor"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/DanTKO"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Flagpole1up"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Ghajestis"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/hennyburgr"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/IsaGoodFriend"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/itsabrody"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Lichtbaulb"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Rue"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Skeleton"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Snas"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/1-Beginner/ZZ-HeartSide"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/aleph_null"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/aridai"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Bonicle"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Clover"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Donker19"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Evilleafy"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/GG19"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Goat"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Hallow"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/hennyburgr"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Lichtbaulb"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Noax"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Oppen_Heimer"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/phant"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/ProXas"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Rocketguy2"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/SilverStar"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Skeleton"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/TheAdvertisement"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/2-Intermediate/ZZ-HeartSide"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/_sleepie"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/BeefyUncle"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Cookie"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Dozing"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Ezel"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Galaksyz"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Holly"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/JaThePlayer"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/LinjKarma"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/NeoKat"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/orbittwz"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Percussive"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/RealVet"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Rufus"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Spoopy"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/taco360"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/Tortoise"
    Mode: 0
  - SID: "SpringCollab2020/3-Advanced/ZZ-HeartSide"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/CANADIAN"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/ChaotiC"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/dahlukeh"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/DeathKontrol"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/deskilln"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Indecx"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Kube"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/LethargicDoggo"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Mineman"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Mun"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/RadleyMcTuneston"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/Zerex"
    Mode: 0
  - SID: "SpringCollab2020/4-Expert/ZZ-HeartSide"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/1nkFa1c0n"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Bissy"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/BobDole"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/CANADIAN"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Cyber"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/DeathKontrol"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/dog"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/fishtank_overflow"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Hydro0"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/iamdadbod"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Problemstrol"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/TheDavSmasher"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/Thegur90"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/ZZ-HeartSide"
    Mode: 0
  - SID: "SpringCollab2020/5-Grandmaster/ZZ-NewHeartSide"
    Mode: 0
