# Rhythm Realm

ASide:
  - Room: "Ezel_00"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
      ReqBoth:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
      
  - Room: "Ezel_01"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
      
  - Room: "Ezel_02"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Right
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "exits"
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: normal
    Subrooms:
    - Room: "exits"
      Holes:
      - Side: Left
        Idx: 1
        Kind: inout
      - Side: Right
        Idx: 1
        Kind: inout
      
  - Room: "Ezel_02b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal
      
  - Room: "Ezel_03"
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
      
  - Room: "Ezel_04"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: out
      ReqOut: # dash block exit
        Dashes: one
    - Side: Up
      Idx: 0
      Kind: out
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: normal
          Flag: poweroff:set
        - Dashes: one
          Difficulty: hard
      
  - Room: "Ezel_04b"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Or:
        - Dashes: one
          Difficulty: hard
        - Dashes: two
          Difficulty: normal
      
  - Room: "Ezel_05"
    Holes:
    - Side: Down
      Idx: 3
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Dashes: one
        Difficulty: hard
    # blocked
    - Side: Left # change respawns can softlock, so have to wall this off lmao
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Up
      Idx: 2
      Kind: none
    - Side: Up
      Idx: 3
      Kind: none
    - Side: Up
      Idx: 4
      Kind: none
    - Side: Up
      Idx: 5
      Kind: none
    - Side: Up
      Idx: 6
      Kind: none
    - Side: Up
      Idx: 7
      Kind: none
    - Side: Up
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 4
      Kind: none
    - Side: Down
      Idx: 5
      Kind: none
    - Side: Down
      Idx: 6
      Kind: none
    - Side: Down
      Idx: 7
      Kind: none
    - Side: Down
      Idx: 8
      Kind: none
    - Side: Down
      Idx: 9
      Kind: none
    - Side: Down
      Idx: 10
      Kind: none
    Tweaks:
    - Name: "exitBlock"
      Update:
        Add: true
        X: 0
        Y: 0
        Width: 848
        Height: 184
        Values:
          tiletype: "6" # Stone
      
  - Room: "Ezel_05b"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Dashes: one
        Difficulty: normal