# Crumbling Castle

ASide:
  - Room: "ATortoise_1"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    # blocked
    - Side: Right
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 0
      Kind: none
    - Side: Down
      Idx: 1
      Kind: none
    - Side: Down
      Idx: 2
      Kind: none
    - Side: Down
      Idx: 3
      Kind: none
    InternalEdges:
    - To: "roof"
      ReqOut:
        Dashes: zero
        Difficulty: normal
      ReqIn:
        Dashes: one
        Difficulty: normal
    - To: "exit"
      ReqOut:
        Key: true
        KeyholeID: 173
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
      ReqIn:
        Key: true
        KeyholeID: 173
        Dashes: one
        Difficulty: normal
    Subrooms:
    - Room: "roof"
      Holes:
      - Side: Up
        Idx: 0
        Kind: inout
    - Room: "exit"
      Holes:
      - Side: Right
        Idx: 0
        Kind: inout
    Tweaks:
    - Name: "spawn"
      X: 120
      Y: 264
      Update:
        Default: true
        
  - Room: "ATortoise_Intro"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - Split: LeftToRight
      ReqBoth:
        Dashes: one
        Difficulty: normal
    Tweaks:
    - Name: "CollabUtils2/SpeedBerry"
      Update:
        Remove: true
    - Name: "CollabUtils2/SilverBerry"
      Update:
        Remove: true
    - Name: "DJMapHelper/maxDashesTrigger"
      Update:
        Remove: true
        
  - Room: "BTortoise_B1"
    Holes:
    - Side: Right
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 1
      Kind: out # dash block
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Up
      Idx: 1
      Kind: none
    - Side: Down # key entrance cut
      Idx: 0
      Kind: none
    InternalEdges:
    - Collectable: 0
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    Subrooms:
    - Room: "cut_key" # workaround until can disable, key not interesting
      Collectables:
      - Idx: 1
      
  - Room: "BTortoise_Outro"
    ReqEnd:
      Dashes: one
      Difficulty: normal
    Holes:
    - Side: Left
      Idx: 0
      Kind: in
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
    - Side: Right
      Idx: 0
      Kind: none
    Tweaks:
    - Name: "CollabUtils2/MiniHeart"
      Update:
        Remove: true
    - Name: "blackGem"
      Update:
        Add: true
        X: 438
        Y: 184
    - Name: "everest/changeInventoryTrigger"
      Update:
        Remove: true
        
  - Room: "CTortoise_B2"
    Collectables:
    - Idx: 0
    Holes:
    - Side: Up
      Idx: 0
      Kind: inout
    # strange
    - Side: Up
      Idx: 1
      Kind: unknown
    # blocked
    - Side: Up
      Idx: 0
      Kind: none
      
  # Tortoise_2 cut, routing doesn't work well in rando :(
        
  - Room: "Tortoise_3"
    Holes:
    - Side: Left # warp-in room
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    Tweaks:
    - Name: "spawn"
      X: 16
      Y: 256
      Update:
        Default: true
      
  - Room: "Tortoise_3B"
    Holes:
    - Side: Right
      Idx: 0
      Kind: in
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    InternalEdges:
    - CustomWarp: true
      ReqOut:
        Dashes: zero
        Difficulty: normal
      
  - Room: "Tortoise_4"
    Holes:
    - Side: Left
      Idx: 1
      Kind: in
    - Side: Right
      Idx: 0
      Kind: inout
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal
    # blocked
    - Side: Left
      Idx: 0
      Kind: none
    - Side: Left
      Idx: 2
      Kind: none # random secret, cut
    - Side: Up
      Idx: 0
      Kind: none
    InternalEdges:
    - To: "berry"
      ReqBoth:
        Key: true
        KeyholeID: 68
    Subrooms:
    - Room: "berry"
      Collectables:
      - Idx: 0
      
  - Room: "Tortoise_5"
    Holes:
    - Side: Left
      Idx: 0
      Kind: inout
    - Side: Right
      Idx: 0
      Kind: inout
    InternalEdges:
    - Split: LeftToRight
      ReqOut:
        Or:
        - Dashes: zero
          Difficulty: hard
        - Dashes: one
          Difficulty: normal